# Generated by Django 3.2.4 on 2022-07-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('sermon_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sermon_title', models.CharField(max_length=100)),
                ('sermon_upload_date', models.DateTimeField()),
                ('sermon_date', models.DateTimeField(null=True)),
                ('sermon_description', models.CharField(max_length=1000)),
                ('sermon_content', models.CharField(max_length=20000)),
                ('sermon_author', models.CharField(max_length=70)),
                ('sermon_location', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
